BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Questions" (
	"Id"	INTEGER NOT NULL,
	"Question"	TEXT NOT NULL,
	"Answer"	TEXT NOT NULL,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Users" (
	"Id"	INTEGER NOT NULL,
	"Name"	TEXT NOT NULL,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Games" (
	"Id"	INTEGER NOT NULL,
	"Name"	TEXT NOT NULL,
	PRIMARY KEY("Id")
);
CREATE TABLE IF NOT EXISTS "GameStatistics" (
	"GameId"	INTEGER NOT NULL,
	"UserId"	INTEGER NOT NULL,
	"Points"	INTEGER NOT NULL,
	PRIMARY KEY("GameId","UserId"),
	FOREIGN KEY("UserId") REFERENCES "Users"("Id"),
	FOREIGN KEY("GameId") REFERENCES "Games"("Id")
);
CREATE TABLE IF NOT EXISTS "UserAliases" (
	"OriginalId"	INTEGER NOT NULL,
	"AliasId"	INTEGER NOT NULL,
	PRIMARY KEY("OriginalId","AliasId"),
	CHECK("OriginalId" <> "AliasId"),
	FOREIGN KEY("OriginalId") REFERENCES "Users"("Id"),
	FOREIGN KEY("AliasId") REFERENCES "Users"("Id")
);
CREATE TABLE IF NOT EXISTS "ScrambledWords" (
	"Id"	INTEGER NOT NULL,
	"Word"	TEXT NOT NULL,
	PRIMARY KEY("Id")
);
CREATE INDEX IF NOT EXISTS "User_Name_Index" ON "Users" (
	"Name"	ASC
);
CREATE INDEX IF NOT EXISTS "Game_Name_Index" ON "Games" (
	"Name"	ASC
);
COMMIT;
